name: Build and Push Docker Image

on:
  workflow_dispatch:    # Allows manually triggering the workflow from the GitHub Actions page
    inputs:                       # Define custom input parameters for the manual trigger
      tags:                       # param
        description: 'Docker Tag' # Description shown in the manual trigger UI
        required: true            # User must provide a value before triggering
        default: 'latest'         # Default value if the user doesn't provide one

  push:                 # Automatically trigger the workflow on push events, when `(branches and paths) or tags` == True
    branches: [main]              # pushing to the 'main' branch
    tags:                         
      - 'v*.*.*'                  # pushing a tag matching the pattern vX.X.X (e.g., v1.2.3)
    paths:                        # changes occur in these specified files or folders
      - audible_epub3_maker/**
      - main.py
      - web_gui.py
      - requirements.txt

jobs:
  build:
    if: ${{ github.repository == 'funway/audible-epub3-maker' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read              # Repository contents
      packages: write             # GitHub Packages, including ghcr.io

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ github.event.inputs.tags || steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true